src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

use App\Repository\AuthorRepository;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 * @Vich\Uploadable()
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private ?string $lastName;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private ?string $firstName;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $birthdate;

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, mappedBy="author")
     */
    private Collection $books;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $filename;

    /**
     * @Vich\UploadableField(mapping="Avatar_image", fileNameProperty="filename")
     */
    private ?File $imageFile;

    /**
     * @ORM\Column (type="date")
     */
    private ?\DateTimeInterface $updateAt;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;
        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): ?self
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updateAt = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt($updateAt): self
    {
        $this->updateAt = $updateAt;
        return $this;
    }


    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            $book->removeAuthor($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFullName(): ?string
    {
        return $this->getFirstName() . " " . $this->getLastName();
    }

    /**
     * @return string|null
     */
    public function getBirthFormat(): ?string
    {
        return $this->getBirthdate()->format("l d F Y");
    }
}

src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

use App\Repository\BookRepository;

/**
 * @UniqueEntity("title")
 * @UniqueEntity("isbn")
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min="4",
     *     minMessage="Il n'y a pas assez de character"
     * )
     *
     */
    private ?string $title;

    /**
     * @ORM\Column(type="text")
     */
    private ?string $synopsis;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $dateParution;

    /**
     * @ORM\Column(type="date")
     */
    private ?\DateTimeInterface $dateEdition;

    /**
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=true,
     *     message="Veuillez entrer un chiffre"
     * )
     * @ORM\Column(type="integer")
     */
    private ?int $nbrPage;

    /**
     *
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false
     * )
     * @ORM\Column(type="string", length=255)
     */
    private ?string $editor;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private ?string $isbn;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private ?string $ean;

    /**
     * @ORM\ManyToMany(targetEntity=Author::class, inversedBy="books")
     */
    private Collection $author;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Genre $genre;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class)
     */
    private Collection $category;

    public function __construct()
    {
        $this->author = new ArrayCollection();
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getDateParution(): ?\DateTimeInterface
    {
        return $this->dateParution;
    }

    public function setDateParution(\DateTimeInterface $dateParution): self
    {
        $this->dateParution = $dateParution;

        return $this;
    }

    public function getDateEdition(): ?\DateTimeInterface
    {
        return $this->dateEdition;
    }

    public function setDateEdition(\DateTimeInterface $dateEdition): self
    {
        $this->dateEdition = $dateEdition;

        return $this;
    }

    public function getNbrPage(): ?int
    {
        return $this->nbrPage;
    }

    public function setNbrPage(int $nbrPage): self
    {
        $this->nbrPage = $nbrPage;

        return $this;
    }

    public function getEditor(): ?string
    {
        return $this->editor;
    }

    public function setEditor(string $editor): self
    {
        $this->editor = $editor;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getEan(): ?string
    {
        return $this->ean;
    }

    public function setEan(string $ean): self
    {
        $this->ean = $ean;

        return $this;
    }

    /**
     * @return Collection<int, author>
     */
    public function getAuthor(): Collection
    {
        return $this->author;
    }

    public function addAuthor(author $author): self
    {
        if (!$this->author->contains($author)) {
            $this->author[] = $author;
        }

        return $this;
    }

    public function removeAuthor(author $author): self
    {
        $this->author->removeElement($author);

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getCategoriesNames(): ?string
    {
        $res = "";
        for ($i = 0; $i < count($this->getCategory()); $i++) {
            $res .= $this->getCategory()[$i]->getLabel();
            $res .= ($i < count($this->getCategory()) - 1) ? (', ') : ('');
        }
        return $res;
    }
}

templates/front/template_part/_booksTemplate.html.twig
<div class="row d-flex flex-row justify-content-between">
    {% for book in books %}
        <div class="card mb-2 d-inline-block" style="width: 30%">
            <div class="card-body">
                <h4 class="card-title">{{ book.title }}</h4>
                <div class="card-text">
                    <p>Auteur :
                        {% set i = 1 %}
                        {% for author in book.author %}
                            {{ author.fullName }} (né le : {{ author.birthFormat }} )
                            {% if i < book.author|length %}
                                ,
                            {% endif %}
                            {% set i = i + 1 %}
                        {% endfor %}
                    </p>
                    <p>ISBN : {{ book.isbn }}</p>
                    <p>Genre : {{ book.genre.label }}</p>
                    <p>Categorie de publication : {{ book.categoriesNames }}</p>
                    <p>Résumé : {{ book.synopsis | excerpt }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

templates/front/template_part/_listeArticles.html.twig
<div class="d-flex flex-row justify-content-start">
    {% for article in articles %}
        <div class="card mb-2 me-2">
            <div class="card-body">
                <h4 class="card-title">
                    {{ article['title'] }}
                </h4>
                <p class="card-text">
                    {{ article['comment'] }}
                </p>
            </div>
        </div>
    {% endfor %}
</div>

templates/front/template_part/_menu.html.twig
<ul class="">
    {% if pp != "home" %}
        <li class="list-unstyled">
            <a href="{{ path("app_home") }}"
               class="btn btn-outline-primary btn-sm mb-2  d-md-block">Accueil</a></li>
    {% endif %}
    {#    {% for num in [1,2,3,4]%} #}
    {#        {% if num != current %} #}
    {#        <li class="list-unstyled"> #}
    {#            <a href="{{ path('app_page', {numPage: num}) }}" #}
    {#                class="  d-md-block btn btn-outline-primary btn-sm mb-2">Voir la page {{ num }}</a> #}
    {#        {% endif %} #}
    {#   </li> #}
    {#    {% endfor %} #}
    {% if pp != "books" %}
        <li class="list-unstyled">
            <a href="{{ path("app_books") }}"
               class="btn btn-outline-primary btn-sm mb-2  d-md-block">Livres</a></li>
    {% endif %}
    <li class="list-unstyled">
        <a href="{{ path("app_author") }}"
           class="btn btn-outline-primary btn-sm mb-2  d-md-block">Auteurs</a></li>
</ul>